service: my-lambda-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

package:
  individually: true

functions:
  chlp:
    handler: backend/chlp.handler
  lambda:
    handler: backend/lambda.handler
  index:
    handler: backend/index.handler