service: my-lambda-service
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  chlp:
    handler: backend/chlp.handler
    package:
      individually: true
  lambda:
    handler: backend/lambda.js
    package:
      individually: true
  index:
    handler: backend/index.js
    package:
      individually: true
