name: Build Lambdas

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      lambda_list: ${{ steps.collect.outputs.lambda_list }}

    steps:
      - uses: actions/checkout@v5

      - name: Install deps
        run: |
          cd backend
          npm install
          npm install -g serverless@3

      - name: Build & Package
        run: |
          sls package
          
      - id: collect  

        run: |  

          files=$(ls .serverless/*.zip | jq -R -s -c 'split("\n")[:-2]')  

          echo "lambda_list=$files" >> $GITHUB_OUTPUT 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zips
          path: .serverless/*.zip

