name: Build Lambdas

on:
  push:
    paths:
      - 'backend/**'
      - 'serverless.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      lambda_list: ${{ steps.collect.outputs.lambda_list }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: |
          cd backend
          npm install
          npm install -g serverless@3

      - name: Package Lambdas
        run: sls package


      - name: List .serverless folder
        run: ls -l .serverless


      - id: collect
        run: |
          files=$( ls | grep *.zip )
          echo "lambda_list=[$files]" >> $GITHUB_OUTPUT


      - name: Upload lambda artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zips
          path: "${{ github.workspace }}/.serverless/*.zip"
